//OFFICIAL UCSD COLOR
--color-accent = #FFCD00

//OFFICIAL UCSD COLOR
--color-primary = #006A96

--color-primary-text = #F7F5E6
--color-primary-text-alt = #000000
--color-primary-lite = #5AA3C1
--color-primary-dark = #005173

//OFFICIAL UCSD COLOR
--color-surface = #747678

--color-surface-text = #FFFFFF
--color-surface-text-alt = #3D3D3D
--color-surface-active = #9A9C9F
--color-surface-lite = #AFA9A0
--color-surface-dark = #4D4D4D
